connectedin/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('perfis.urls')),
    url(r'^', include('usuarios.urls')),
    url(r'^', include('posts.urls'))
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from posts import views

urlpatterns = [
	url(r'^post$', views.post, name='post'),
	url(r'^post/(?P<post_id>\d+)/deletar$', views.delete, name='delete_post'),
	url(r'^post/(?P<post_id>\d+)/like$', views.like, name='like')
] 

usuarios/urls.py
from django.conf.urls import url
from usuarios.views import RegistrarUsuarioView, procurar
from django.contrib.auth import views
 
urlpatterns = [
	url(r'^registrar/$', RegistrarUsuarioView.as_view(), name='registrar'),
	url(r'^procurar/$', procurar, name='procurar'),
	url(r'^login/$', views.LoginView.as_view(template_name='login.html'), name='login'),
   	url(r'^logout/$', views.LogoutView.as_view(template_name='login.html'), name='logout'),
   	url(r'^password_change/$', views.PasswordChangeView.as_view(template_name='change_password.html'), name='change_password'),
]

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):

	nome = forms.CharField(required=True)
	email = forms.EmailField(required=True)
	senha = forms.CharField(required=True)
	telefone = forms.CharField(required=True)
	nome_empresa = forms.CharField(required=True)

	def is_valid(self):
		valid = True
		if not super(RegistrarUsuarioForm, self).is_valid():
			self.adiciona_erro('Por favor verifique os dados informados')
			valid = False

		user_exists = User.objects.filter(username=self.data['nome']).exists()

		if user_exists:
			self.adiciona_erro('Usuario ja existente')
			valid = False

		return valid

	def adiciona_erro(self, message):
		errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
		errors.append(message)	 

class ProcurarForm(forms.Form):
	username = forms.CharField(required=True)

	def is_valid(self):
		valid = True
		if not super(ProcurarForm, self).is_valid():
			self.adiciona_erro('Por favor verifique os dados informados')
			valid = False

		return valid

usuarios/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic.base import View
from perfis.models import Perfil
from usuarios.forms import RegistrarUsuarioForm, ProcurarForm

class RegistrarUsuarioView(View):
	
	template_name = 'registrar.html'

	def get(self, request):
		return render(request, self.template_name)

	def post(self, request):
		
		form = RegistrarUsuarioForm(request.POST)
		
		if form.is_valid():
		
			dados_form = form.data

			usuario = User.objects.create_user(username=dados_form['nome'], email=dados_form['email'], password=dados_form['senha'])

			perfil = Perfil(nome=dados_form['nome'], telefone=dados_form['telefone'], nome_empresa=dados_form['nome_empresa'], usuario=usuario)

			perfil.save()
		
			return redirect('index')

		return render(request, self.template_name, {'form' : form})

def procurar(request):
	form = ProcurarForm(request.POST)

	if form.is_valid():
		dados_form = form.data
		
		perfis = Perfil.objects.filter(nome__contains= dados_form['username'])
		perfil_logado = request.user.perfil
		return render(request, 'procurar.html', { "perfis" : perfis, "perfil_logado": perfil_logado })
	return redirect('index')

usuarios/templates/base_usuario.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<title>ConnectedIn</title>
	<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/signin.css' %}">
</head>
<body>
	<div class="container">
		{% block body %}
		{% endblock %}
	</div>
</body>
</html>

usuarios/templates/change_password.html
{% extends "base_usuario.html" %}

{% block body %}
	
	<form action="" class="form-signin" role="form" method="post">
		{% csrf_token %}
		<h2 class="form-signin-heading">Change Password</h2>

		<input type="password" class="form-control" id="id_oldpassword" name="old_password" placeholder="Old Password" required autofocus>

		<input type="password" class="form-control" id="id_new_password1" name="new_password1" placeholder="New Password" required>
		
		<input type="password" class="form-control" id="id_new_password2" name="new_password2" placeholder="Confirm Password" required>


		<button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Change</button>

		<input type="hidden" name="next" value="{{ next }}">

		{% if form.errors %}
			<div class="alert alert-danger">
				<button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
				{{ form.errors }}
			</div>
		{% endif %}
	</form>

{% endblock %}

usuarios/templates/login.html
{% extends "base_usuario.html" %}

{% block body %}

    <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus>

        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

        <input type="hidden" name="next" value="{{ next }}" />

        {% if form.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Por favor, verifique o Email e/ou Senha informados
          </div>
        {% endif %}

        <a href="{% url 'registrar' %}">registre-se</a>
    </form>

{% endblock %}

usuarios/templates/procurar.html
{% extends "base.html" %}
{% block body %}
<div class="col-lg-12">	
	<div id="usuarios-tab">
		<div class="panel panel-default" id="usuarios-tab">
			<div class="panel-heading">
				<strong>Resultado da Busca</strong>
			</div>
			{% if perfis %}
			<ul>
				{% for perfil in perfis %}
				<li>
				<a href="{% url 'exibir' perfil.id %}">{{ perfil.nome }} / {{ perfil.email }}</a>
				<a href="{% url 'convidar' perfil.id %}" class="pull-right">Convidar</a>
				</li>
				{% endfor %}
			</ul>
			{% else %}
			<p>Nenhum Perfil encontrado!</p>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

usuarios/templates/registrar.html
{% extends "base_usuario.html" %}
{% block body %}
	<form class="form-signin" action="{% url 'registrar' %}" method="post">
		{% csrf_token %}
		<h2 class="form-signin-heading">Crie seu usuário</h2>

		<input id="id_email" type="text" name="email" class="form-control" placeholder="Email *" value="{{ form.email.value }}" required>
		<input id="id_nome" type="text" name="nome" class="form-control" placeholder="Nome *" value="{{ form.nome.value }}" required>
		<input id="id_senha" type="password" name="senha" class="form-control" placeholder="Senha *" required>
		<input id="id_telefone" type="text" name="telefone" class="form-control" placeholder="Telefone" value="{{ form.telefone.value }}">
		<input id="id_nome_empresa" type="text" name="nome_empresa" class="form-control" placeholder="Empresa" value="{{ form.nome_empresa.value }}">

		<hr>
		{% if form.errors %}
			<div class="alert alert-danger">
				<button type="button" class="close">&times;</button>
				{{form.non_field_errors}}
			</div>
		{% endif %}
		<button class="btn btn-lg btn-primary btn-block" type="subimit">Registar</button>
	</form>
{% endblock %}